backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    # https://www.netlifycms.org/docs/beta-features/#nested-collections
    nested:
      depth: 100
      # summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "image", widget: "image"}
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Draft", name: "draft", widget: "boolean"}
